logging:
  level:
    org.zalando.logbook: TRACE

spring:
  datasource:
    url: jdbc:h2:file:./db/filmorate;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:/schema.sql